// <auto-generated />
namespace ESTReporting.EntityModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddColumn_EST_BAM_ModelLookup__EsteemAltCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumn_EST_BAM_ModelLookup__EsteemAltCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201809281108431_AddColumn_EST_BAM_ModelLookup__EsteemAltCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
