// <auto-generated />
namespace ESTReporting.EntityModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_ESTAudit_BaseClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_ESTAudit_BaseClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201808310821109_Added_ESTAudit_BaseClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
